version: '3.8'

services:
  # api service configuration
  backend_django:
    # django project folder
    build: ./myproject
    # using bash script to migrate database and start the app
    command: sh /entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db


  frontend_django:
    build: ./frontend_django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=django_tasks

volumes:
  postgres_data: