# Generated by Django 5.0.6 on 2024-06-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
