# Generated by Django 5.0.6 on 2024-06-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
