# Generated by Django 5.0.6 on 2024-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_description_remove_task_title_task_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
